name: 'Docsington'
description: 'Wait a designated number of milliseconds'
inputs:
  words:  # id of input
    description: 'Random word'
    required: true
    default: 'hello world'
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
